export default {
  locale: 'en',
  messages: {
    siteTitle: 'Application form',
    switchLanguage: ' ',
    draftFormTitle: 'Application form',
    inputTooLong: 'Input is too long.',
    draftSenderName: 'Your first and last name',
    draftSenderNameInvalid: 'First and last names must be at least 5 characters combined.',
    draftSenderEmail: 'Your own email address',
    draftSenderEmailInvalid: 'Email is invalid.',
    draftSenderConfirmEmail: 'Confirm email address',
    draftSenderConfirmEmailInvalid: 'Emails do not match.',
    draftSenderOrganisation: 'School and role (teacher/student) or profession',
    draftSenderOrganisationInvalid: 'Input is not long enough.',
    draftMembers: 'Size of the team',
    draftMembersDefault: 'Select the amount of total members in your team',
    persons: 'members',
    draftMembersInvalid: 'Attention! The minimum team size for participation is two members.',
    draftTitle: 'Title for the idea',
    draftTitleInvalid: 'Title must be at least 5 characters long.',
    draftDescription: 'Idea description ',
    draftDescriptionInvalid: 'The description is not long enough.',
    draftHeardFrom: 'How did you hear about competition?',
    draftHeardFromInvalid: 'Input is not long enough.',
    draftPdfLabel: 'Attachment',
    draftPdfInfo: 'Drop the file here or click to open the file browser',
    draftPdfExtension: 'Only *.pdf files will are accepted',
    draftPdfRejected: 'Rejected file',
    draftPdfRejectedAlert: 'The file was rejected, it is too large or not in the .pdf format.',
    draftTerms: 'I accept the terms & conditions and the cookie policy',
    termsModalTitle: 'Terms & conditions and cookie policy',
    termsTitle: 'Terms & conditions',
    cookiesTitle: 'Cookie policy',
    cookiesInfo: 'Some of the pages functionality depends on the usage of cookies.\n\n' +
    'Google uses cookies to provide the reCAPTCHA service used to protect against forms sent by bots.\n' +
    'More information of these cookies can be found from the links attached to the reCAPTCHA logo.\n\n' +
    'TinyMCE is a text editor, which is used to write the description. TinyMCE cookies are used to change the size of the text-area ' +
    'dynamically.',
    submit: 'Submit',
    formIncomplete: 'Verify that all of the fields are filled correctly.',
    submitError: 'There was an error in submitting the form, please try again.',
    descriptionTooLong: 'Error! The description exceeds the editors maximum limit of 75000 characters.',
    close: 'Close',
    formSubmitted: 'Form has been submitted',
    formSentText: 'Your application has been sent. You will receive an confirmation email, but it does not contain the application ' +
    'details, thus you should save any details you wish to save before closing this popup.',
  },
};
