export default {
  locale: 'fi',
  messages: {
    siteTitle: 'Hakulomake',
    switchLanguage: ' ',
    draftFormTitle: 'Hakemus',
    inputTooLong: 'Syöte on liian pitkä.',
    draftSenderName: 'Etu- ja sukunimi',
    draftSenderNameInvalid: 'Etu- ja sukunimien pituuden on oltava yhteensä vähintään 5 merkkiä.',
    draftSenderEmail: 'Sähköpostiosoitteesi',
    draftSenderEmailInvalid: 'Tarkista sähköpostiosoite.',
    draftSenderConfirmEmail: 'Sähköpostin vahvistus',
    draftSenderConfirmEmailInvalid: 'Sähköpostiosoitteet eivät täsmää.',
    draftSenderOrganisation: 'Oppilaitos ja asema (oppilas/opettaja) tai ammatti',
    draftSenderOrganisationInvalid: 'Kirjoita tähän mitä oppilaitosta tai työpaikkaa/ammattia edustat.',
    draftMembers: 'Tiimin koko',
    draftMembersDefault: 'Valitse tiimiläisten määrä',
    persons: 'henkilöä',
    draftMembersInvalid: 'Huom! Osallistuminen vaatii vähintään kahden hengen tiimin.',
    draftTitle: 'Idean nimi',
    draftTitleInvalid: 'Idean otsikon on oltava vähintään 5 merkkiä pitkä.',
    draftDescription: 'Idean kuvaus ',
    draftDescriptionInvalid: 'Idean kuvaus ei ole tarpeeksi pitkä.',
    draftHeardFrom: 'Miten kuulit kilpailusta?',
    draftHeardFromInvalid: 'Kerro miten sait tietää kilpailusta.',
    draftPdfLabel: 'Liitetiedosto',
    draftPdfInfo: 'Pudota tiedosto tähän tai avaa tiedoston valinta klikkaamalla.',
    draftPdfExtension: 'Ainoastaan *.pdf tiedostot hyväksytään.',
    draftPdfRejected: 'Virheellinen tiedosto',
    draftPdfRejectedAlert: 'Tiedosto hylättiin, sen koko on liian suuri tai se ei ole kelvollinen .pdf-tiedosto.',
    draftTerms: 'Hyväksyn palvelun käyttöehdot ja evästeiden käytön',
    termsModalTitle: 'Käyttöehdot ja evästeet',
    termsTitle: 'Käyttöehdot',
    cookiesTitle: 'Evästeiden käyttö',
    cookiesInfo: 'Osa sivuston toiminnallisuudesta on kytköksissä evästeisiin.\n\n' +
    'Googlen evästeitä tarvitaan reCAPTCHA palvelua varten, joka suojelee lomaketta robotteja vastaan.\n' +
    'Lisätietoa näistä evästeistä saa reCAPTCHA logoon liitettyjen linkkien kautta.\n\n' +
    'TinyMCE on tekstieditori, jota käytetään kuvauksen kirjoittamiseen. TinyMCE käyttää evästeitä tekstikentän ' +
    'koon dynaamiseen muuttamiseen.',
    submit: 'Lähetä',
    formIncomplete: 'Tarkista, että kaikki kentät on täytetty oikein.',
    submitError: 'Hakemuksen lähettämisessä tapahtui virhe. Yritä lähettää hakemus uudestaan.',
    descriptionTooLong: 'Hakemusta ei lähetetty! Kuvaus on liian pitkä ja ylittää tekstieditorin 75000 merkin rajan.',
    close: 'Sulje',
    formSubmitted: 'Hakemus lähetetty',
    formSentText: 'Hakemuksesi lähetettiin onnistuneesti. Saat sähköpostiisi vielä vahvistusviestin, viesti ei sisällä ' +
    'hakemuksen tietoja.\nJos haluat säilyttää tiedot, ota ne itsellesi nyt talteen.',
  },
};
